name: AgendaCloud
version: 3.0.0-SNAPSHOT
main: cat.kiwi.minecraft.acloud.AgendaCloudPlugin
load: STARTUP
authors: [ moeKiwiSAMA ]
description: Service register
api-version: 1.12
commands:
    acloud:
        description: Service register
        usage: /acloud query>
        aliases: [ acloud ]